name: Security Scan

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read
  pull-requests: write
  checks: write
  security-events: write

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Oculum Security Scan
        uses: OculumDev/oculum-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          depth: cheap
          fail-on: none       # Never fail the workflows
      - name: CodeQL and Dependabot Report Action
        uses: rsdmike/github-security-report-action@v3.0.4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}